### ISSUE TITLE
Schema unavailable 

### ISSUE THREAD

**Issue by Tarektouati** [DockStation/dockstation#110]
<img width="1201" alt="capture d ecran 2018-03-05 a 12 36 24" src="https://user-images.githubusercontent.com/19335073/36973241-71b394e2-2072-11e8-8a7e-c5eb2a44b6ce.png">
schema panel keep loading, doesn't display anything

**Comment by igor-lemon** [comment]
Hi @Tarektouati, I couldn't reproduce it. It can calls if you have some connection troubles. Try to switch Docker Hub/Local images.

**Comment by Tarektouati** [comment]
I already tried to switch between hub and local images and doesn't work 
my docker version : Version 18.03.0-ce-rc1-mac54 (23022), Channel: edge, e10c72243a

**Comment by igor-lemon** [comment]
Did you try to close and reopen app?

**Comment by Tarektouati** [comment]
yeah already tried it , problem is still there

**Comment by igor-lemon** [comment]
Try to open
`https://gist.githubusercontent.com/DockStation/02cf82e76dabff050631e35d7ac20813/raw/edc7d3531c4f71f0a66e6c5bf8eb000e0f3128ce/recommended.json`

Do you have an array of Images?

**Comment by igor-lemon** [comment]
Please, try on new version again

**Comment by Tarektouati** [comment]
I have installed you're new version and nothing work,  i got
![capture d ecran 2018-03-27 a 09 47 48](https://user-images.githubusercontent.com/19335073/37953811-432526b6-31a4-11e8-99b1-608997e30e66.png)
 a white windows

**Comment by igor-lemon** [comment]
O_o
What is your OS version?
Did you update via updater or did you download new DMG?

**Comment by Tarektouati** [comment]
OS version : MacOS High Sierra 10.13.3 (17D102), my Docker version : 18.03.0-ce-rc4-mac57 (23360) Channel: edge, i downloaded a new dmg

**Comment by alexandrevilain** [comment]
Hi! 
It's quite strange, I've got the same OS version than @Tarektouati :
MacOS: 10.13.3 (17D102)
But my Docker Version is :
Docker: 18.03.0-ce-mac58 (23607)

And it works well!
@Tarektouati do you have anything in ~/Library/Logs/DockStation ?

**Comment by igor-lemon** [comment]
Huh... 
We'll check on another Mac

**Comment by igor-lemon** [comment]
![image](https://user-images.githubusercontent.com/14764799/37954819-97bd2506-31af-11e8-9e29-4d21bbf72bc9.png)
:(

**Comment by igor-lemon** [comment]
@alexandrevilain @Tarektouati
Please, try to stop Docker and return the app. Do you have an error about stopped Docker?

**Comment by Tarektouati** [comment]
@igor-lemon  I've made a new install of Dockstation, it's worked, but when i clicked on schema i got the white screen.
I have nothing in the logs

**Comment by alexandrevilain** [comment]
Why isn't the source code for this app open-sourced? 
No one can help you and it would be a pleasure to help you.

**Comment by igor-lemon** [comment]
@Tarektouati It's strange. 
Ok. Can you share me your Docker Compose config?

**Comment by Tarektouati** [comment]
Here's the docker-compose file :  
```
version: '3'
services:
  postgres:
    image: 'postgres:9.4'
    volumes:
      - './users.sql:/docker-entrypoint-initdb.d/users.sql'
    restart: always
    environment:
      POSTGRES_PASSWORD: pwd
      POSTGRES_USER: usr
      POSTGRES_DB: db
    ports:
      - '5432:5432'
  dynamodb:
    image: dwmkerr/dynamodb
    restart: always
    ports:
      - '8000:8000'
  svc1:
    image: 'registry/svc1:latest'
    ports:
      - '4001:4001'
  sv2:
    image: 'registry/svc2:latest'
    depends_on:
      - dynamodb
      - svc1
    ports:
      - '4000:4000'
    links:
      - svc1
      - dynamodb
    environment:
      - 'SVC1=http://svc1:4001'
      - 'DYNAMODB_ENDPOINT=http://dynamodb:8000'
  svc3:
    image: 'registry/svc3:latest'
    restart: always
    depends_on:
      - postgres
      - svc1
    ports:
      - '4002:4002'
    links:
      - svc1
      - 'postgres:db'
    environment:
      - 'SVC1=http://svc1:4001'
      - 'POSTGRES_CONNECTIONSTRING=postgres://usr:pwd@db:5432/db'
  svc4:
    image: 'registry/svc4:latest'
    depends_on:
      - svc1
      - svc5
    environment:
      - 'ListenAddress=0.0.0.0:9000'
    ports:
      - '9000:9000'
    links:
      - svc5
      - svc1
      - sv2
  svc5:
    image: 'registry/svc5:latest'
    volumes:
      - '.:/tmp'
    ports:
      - '7000:7000'
```
Sorry but i had to change the names of services.
