### ISSUE TITLE
Unix to Windows path conversion

### ISSUE THREAD

**Issue by asliwinski** [DockStation/dockstation#130]
I cannot select and copy the logs (which is another issue), so I'm pasting a screenshot:
![image](https://user-images.githubusercontent.com/14044823/44507795-86547f80-a671-11e8-915f-98e7ca4d2bc0.png)
This is a known issue and setting environmental variable COMPOSE_CONVERT_WINDOWS_PATHS=1 solves the problem when running the container directly, however it doesn't work in dockstation.

The image: https://hub.docker.com/r/jwilder/nginx-proxy/

**Comment by asliwinski** [comment]
Hi @igor-lemon, here's the relevant section of my docker-compose.yml:

```
  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    ports:
      - "443:443"
    networks:
      app_net:
        ipv4_address: 172.16.111.111  
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
      - ./nginx/certificates:/etc/certificates:ro
```

So the volumes are defined and this configuration is reflected in Dockstation in the tab you showed on your screenshot. As I said, this is a known bug and setting the environmental variable to convert the path solves the problem, however the environmental variable somehow doesn't affect Dockstation, as if it was an isolated environment.
