### ISSUE TITLE
Doesn't work with multiple docker-compose files based app 

### ISSUE THREAD

**Issue by ryuheechul** [DockStation/dockstation#47]
<img width="912" alt="screen shot 2017-07-25 at 11 38 10 am" src="https://user-images.githubusercontent.com/2637709/28553294-d5c22f56-712d-11e7-8805-82d1fe1b8c87.png">

There are docker-compose.override.yml exist.
So it should work with dockstation, since it works well with commands

**Comment by igor-lemon** [comment]
@ryuheechul check a path to Dockerfile.

**Comment by igor-lemon** [comment]
Hi @ryuheechul. We'll add a possibility to work with an override compose config in the next release.

**Comment by igor-lemon** [comment]
Released into v1.3

**Comment by moonion** [comment]
It doesn't work for me :( 
When I create new project and select paths where exist docker-compose.yml and docker-compose.override.yml. Because my project can't be run without docker-compose.override.yml.

MacOS.
![screen](https://download.nashivan.pp.ua/DockStation_2017-09-21_23-10-38.jpg)

**Comment by igor-lemon** [comment]
Hi @moonion 
Can you share your `docker-compose.yml` and `docker-compose.override.yml` configs ?
Also thanks for a bug with button layers...

**Comment by igor-lemon** [comment]
Also call `docker-compose config` command into the directory with your configs and share screenshot. Thank you.

**Comment by moonion** [comment]
I replaced ` /.../` and `registry/`

docker-compose.yml
```yaml
version: '2'
services:
  app:
  backend:
    links:
      - db
    environment:
      - DB_DATABASE=test
      - DB_HOST=db
      - DB_USERNAME=test
      - DB_PASSWORD=test
    volumes:
      - './data/uploads/images:/var/www/html/uploads/images'
      - './data/uploads/staff/images:/var/www/html/uploads/staff/images'
      - './data/uploads/videos:/var/www/html/uploads/videos'
  db:
    image: mariadb
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=test
    volumes:
      - './data/mysql:/var/lib/mysql'
  nginx:
    image: registry/docker/nginx
    depends_on:
      - app
      - backend
    volumes_from:
      - 'app:ro'
      - 'backend:ro'
```

docker-compose.override.yml
```yaml
version: "2"
services:
  app:
    build:
      context: ../app
      dockerfile: Dockerfile.local
    volumes:
      - ../app/src:/usr/src/src
  backend:
     image: registry/test/backend
  nginx:
    ports:
      - "80:80"
```

docker-compose config
```yaml
services:
  app:
    build:
      context: /.../test/app
      dockerfile: Dockerfile.local
    volumes:
    - /.../test/app/src:/usr/src/src:rw
  backend:
    environment:
      DB_DATABASE: test
      DB_HOST: db
      DB_PASSWORD: test
      DB_USERNAME: test
    image: registry/test/backend
    links:
    - db
    volumes:
    - /.../data/uploads/images:/var/www/html/uploads/images:rw
    - /.../data/uploads/staff/images:/var/www/html/uploads/staff/images:rw
    - /.../data/uploads/videos:/var/www/html/uploads/videos:rw
  db:
    environment:
      MYSQL_DATABASE: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: test
    image: mariadb
    volumes:
    - /.../data/mysql:/var/lib/mysql:rw
  nginx:
    depends_on:
    - app
    - backend
    image: registry/docker/nginx
    ports:
    - 80:80/tcp
    volumes_from:
    - service:app:ro
    - service:backend:ro
version: '2.0'
```
